const PDFDocument = require('pdfkit');
const Document = require('../models/Document');

exports.downloadDocumentPDF = async (req, res) => {
  try {
    const docData = await Document.findById(req.params.id)
      .populate('landlordId', 'firstName lastName phone')
      .populate('tenantId', 'firstName lastName email phone')
      .populate('propertyId');

    const pdf = new PDFDocument({ margin: 50 });
    
    // Set headers for download
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=Lease_${docData._id}.pdf`);
    pdf.pipe(res);

    // Header & Brand
    pdf.fillColor('#54ab91').fontSize(25).text('URUGO RENTAL AGREEMENT', { align: 'center' });
    pdf.moveDown();
    pdf.fillColor('#444').fontSize(10).text(`System Reference: ${docData._id}`, { align: 'center' });
    pdf.text('Verification Status: Urugo Verified Digital Record', { align: 'center' });
    pdf.moveDown(2);

    // Section 1: The Parties
    pdf.fillColor('#000').fontSize(14).text('1. THE PARTIES', { underline: true });
    pdf.fontSize(10).text(`Landlord: ${docData.landlordId.firstName} ${docData.landlordId.lastName} | Phone: ${docData.landlordId.phone}`);
    pdf.text(`Tenant: ${docData.tenantId.firstName} ${docData.tenantId.lastName} | Phone: ${docData.tenantId.phone}`);
    pdf.moveDown();

    // Section 2: The Property
    pdf.fontSize(14).text('2. THE PROPERTY', { underline: true });
    pdf.fontSize(10).text(`Property: ${docData.propertyId.name} | Unit: ${docData.unitNumber || 'N/A'}`);
    pdf.text(`Location: Kigali, Rwanda`);
    pdf.moveDown();

    // Section 3: Financials
    pdf.fontSize(14).text('3. RENT & FINANCIAL TERMS', { underline: true });
    pdf.fontSize(10).text(`Monthly Rent: ${docData.rentAmount || 0} RWF`);
    pdf.text(`Payment Method: Urugo Wallet (MoMo/Card)`);
    pdf.moveDown();

    // Footer & Auth
    pdf.moveDown(5);
    pdf.fontSize(8).fillColor('#999').text(`Generated by Urugo System on ${new Date().toLocaleDateString()}`, { align: 'center' });
    pdf.text('Electronic Signatures Verified via System Login', { align: 'center' });

    pdf.end();
  } catch (error) {
    res.status(500).json({ message: "PDF Generation Failed" });
  }
};