const express = require('express');
const router = express.Router();
const { protect, landlordOnly } = require('../middleware/authMiddleware');
const Document = require('../models/Document');

console.log('documentRoutes middleware types:', typeof protect, typeof landlordOnly);

// Get all documents for the logged-in user (landlord or tenant)
router.get('/', protect, async (req, res) => {
  try {
    const documents = await Document.find({ ownerId: req.userId }).sort({ createdAt: -1 });
    res.json({ success: true, documents });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});


// Get a single document by ID
router.get('/:id', protect, async (req, res) => {
  try {
    const document = await Document.findOne({
      _id: req.params.id,
      ownerId: req.userId
    });

    if (!document) {
      return res.status(404).json({ message: 'Document not found' });
    }

    res.json({ success: true, document });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// Generate and return a lease agreement document (view/download)
const { generateLeaseDocument } = require('../services/documentService');
router.get('/lease/:leaseId', protect, async (req, res) => {
  try {
    const doc = await generateLeaseDocument(req.params.leaseId);
    // Updated template to show all identifying info
    const template = `# RESIDENTIAL RENTAL AGREEMENT\n**System Reference:** \\${doc.referenceNo}\n**Verification Status:** Urugo Verified Digital Record\n\nThis Digital Rental Agreement ("Agreement") is formally generated on **\\${doc.dateGenerated.toLocaleDateString()}** following the approval of a Rental Request through the Urugo Platform.\n\n### 1. THE PARTIES\n**Landlord:**\n* **Name:** \\${doc.content.parties.landlord.name}\n* **Email:** \\${doc.content.parties.landlord.email}\n* **Phone:** \\${doc.content.parties.landlord.phone}\n* **System ID:** \\${doc.content.parties.landlord.systemId}\n* **National ID:** \\${doc.content.parties.landlord.nationalId}\n* **Passport Number:** \\${doc.content.parties.landlord.passportNumber}\n\n**Tenant:**\n* **Name:** \\${doc.content.parties.tenant.name}\n* **Email:** \\${doc.content.parties.tenant.email}\n* **Phone:** \\${doc.content.parties.tenant.phone}\n* **System ID:** \\${doc.content.parties.tenant.systemId}\n* **National ID:** \\${doc.content.parties.tenant.nationalId}\n* **Passport Number:** \\${doc.content.parties.tenant.passportNumber}\n\n### 2. THE PROPERTY\nThe Landlord hereby agrees to rent to the Tenant the following premises:\n* **Property Name:** \\${doc.content.property.name}\n* **Unit Number:** \\${doc.content.property.unitNumber}\n* **Location:** \\${doc.content.property.address}\n* **Property Type:** \\${doc.content.property.propertyType}\n\n### 3. TERM & DURATION\nThe rental period shall commence on **\\${doc.content.duration.split(' to ')[0]}** and remain active until **\\${doc.content.duration.split(' to ')[1]}**, unless terminated in accordance with the terms herein. This record is synchronized with the **Renters** management dashboard.\n\n### 4. RENT & FINANCIAL TERMS\n* **Monthly Rent:** **\\${doc.content.rent}**\n* **Payment Due Date:** On or before the **5th** of each month.\n* **Payment Method:** Exclusively via the **Urugo Wallet** (Stripe/Flutterwave/MoMo).\n* **Late Penalties:** A weekly penalty of **5%** shall automatically accrue on the **Transactions** dashboard for payments exceeding the grace period.\n\n### 5. DIGITAL ONBOARDING & TRUST\n* **Account Access:** Upon generation of this agreement, the Tenant is granted credentials to the Urugo Dashboard using their registered email.\n* **Urugo Trust Score:** Payment performance under this lease will directly impact the Tenant's **Urugo Trust Score** (0-100), affecting future rental applications within the network.\n* **Verification:** This lease is mapped to the Tenant's verified 16-digit Rwandan National ID.\n\n### 6. MAINTENANCE & UTILITIES\n* **Utilities:** The Tenant is responsible for all utility charges including Water, Electricity (CashPower), and Internet unless otherwise specified.\n* **Condition:** The Tenant must maintain the unit in the condition received. Structural repairs remain the responsibility of the Landlord.\n\n### 7. DIGITAL RECORD & ARCHIVE\nThis agreement is digitally archived and cannot be tampered with. It is accessible at any time via the **Documents** section of the Urugo Platform for both parties.\n\n### 8. GOVERNING LAW\nThis Agreement shall be governed by and interpreted according to the laws of the Republic of Rwanda.\n\n---\n**Digital Authentication:**\n*Generated by Urugo Rental Management System on \\${doc.dateGenerated.toLocaleDateString()}.*\n*Electronic signature of Landlord: [Verified via System Login]*\n*Electronic signature of Tenant: [Verified via System Login]*`;
    res.setHeader('Content-Type', 'text/markdown');
    res.setHeader('Content-Disposition', `attachment; filename=lease-agreement-${doc.referenceNo}.md`);
    res.send(template);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// Create a new document
router.post('/', protect, landlordOnly, async (req, res) => {
  try {
    const document = await Document.create({
      ...req.body,
      ownerId: req.userId
    });

    res.status(201).json({ success: true, document });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// Update a document
router.put('/:id', protect, landlordOnly, async (req, res) => {
  try {
    const document = await Document.findOne({
      _id: req.params.id,
      ownerId: req.userId
    });

    if (!document) {
      return res.status(404).json({ message: 'Document not found' });
    }

    const updatedDocument = await Document.findByIdAndUpdate(
      req.params.id,
      { $set: req.body },
      { new: true }
    );

    res.json({ success: true, document: updatedDocument });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// Delete a document
router.delete('/:id', protect, landlordOnly, async (req, res) => {
  try {
    const document = await Document.findOne({
      _id: req.params.id,
      ownerId: req.userId
    });

    if (!document) {
      return res.status(404).json({ message: 'Document not found' });
    }

    await Document.findByIdAndDelete(req.params.id);
    res.json({ success: true, message: 'Document deleted successfully' });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

module.exports = router;
